config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  get "home/about"=>"homes#about"
  get "search" => "searches#search"
    devise_for :users

  resources :users, only: [:index,:show,:edit,:update]
  
  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create,:destroy]
    resources :book_comments, only: [:create,:destroy]
  end
  
  resources :user do
    resource :relationships, only: [:create,:destroy]
    get "followings" => "relationships#followings", as: "followings"
    get "followers" => "relationships#followers", as: "followers"
  end

  resources :rooms, only: [:show]
  resources :chats, only: [:index,:create]
  
  resources :groups, only: [:new,:index,:show,:edit,:create,:destroy,:update] do
    resource :group_users, only: [:create,:destroy]
    resources :event_notices, only: [:new, :create]
    get "event_notices" => "event_notices#sent"
  end
  
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name,length:{minimum:2,maximum:20},uniqueness:true
  validates :introduction,length:{maximum:50}

  has_one_attached :profile_image
  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :book
  has_many :book_comments, dependent: :destroy
  has_many :group_users, dependent: :destroy
  
  # 自分がフォローする（与フォロー）側の関係性
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 自分がフォローされる（被フォロー）側の関係性
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 与フォロー関係を通じて参照→自分がフォローしている人
  has_many :followings, through: :relationships, source: :followed
  # 被フォロー関係を通じて参照→自分をフォローしている人
  has_many :followers, through: :reverse_of_relationships, source: :follower
  
  has_many :user_rooms
  has_many :rooms, through: :user_rooms
  has_many :chats
  #throughオプションによりuser_rooms(中間テーブル)経由でroomsにアクセスできるようになる
  #user.roomsでアクセスができる
  
  # フォローしたときの処理
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  # フォローを外すときの処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end
  
  # 検索方法の分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end
  
  def self.guest
    find_or_create_by!(name: 'guestuser' ,email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end
  
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
    
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: 'guestuserでログインしました。'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:edit,:update]
  before_action :ensure_guest_user, only: [:edit]

  def show
    @user = User.find(params[:id])
    @nbook = Book.new
    @books = @user.books
    @users = User.all
    @today_book = @books.created_today
    @yesterday_book = @books.created_yesterday
    @this_week_book = @books.created_this_week
    @last_week_book = @books.created_last_week
    @days_ago = @books.create_week_count
  end

  def index
    @users = User.all
    @nbook = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
  
  def ensure_guest_user
    @user = User.find(params[:id])
    if @user.name == "guestuser"
      redirect_to user_path(current_user) , notice: 'ゲストユーザーはプロフィール編集画面へ遷移できません。'
    end
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td>フォロー数:<%= user.followings.count %></td>
        <td>フォロワー数:<%= user.followers.count %></td>
        <td>
          <% if current_user.following?(user) %>
              <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
            <% else %>
              <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
          <% end %>
        </td>
        <td><%= link_to 'Show', user %></td> 
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th><%= link_to user.followings.count, user_followings_path(user) %></th>
  </tr>
  <tr>
    <th>followers</th>
    <th><%= link_to user.followers.count, user_followers_path(user) %></th>
  </tr>
</table>

<div>
  <% if user.name == "guestuser" %>
    <!-- 何も表示しない -->
  <% elsif user == current_user %>
      <%= link_to edit_user_path(user), class:'btn btn-outline-secondary btn-block' do %>
        <i class='fas fa-user-cog'></i>
      <% end %>
    <% elsif current_user.following?(user) && user.following?(current_user) %>
       <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class:'btn btn-info'%>
      <%= link_to "Chatを始める", room_path(user), class:'btn btn-outline-info'%>
    <% elsif current_user.following?(user) %>
      <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class:'btn btn-info'%>
    <% else %>
      <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class:'btn btn-success'%>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :mame %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: current_user %>
      <h2 class='mt-3'>New book</h2>
      <%= render 'books/form', book: @nbook %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
      <%= link_to "グループを作成する", new_group_path %> | <%= link_to "グループ一覧", groups_path %>
      <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @nbook %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
    
<!--投稿数カウント-->
      <div class = 'table_width'>
        <h3>投稿数の前日比・前週比</h3>
        <table class="table table-bordered text-center">
          <thead>
            <tr>
              <th>今日の投稿数</th>
              <th>前日の投稿数</th>
              <th>前日比</th>
            </tr>
          </thead>
          <tbody>
            <tr>
           　  <td><%= @today_book.count %></td>
           　  <td><%= @yesterday_book.count %></td>
           　  <td>
                <% if @yesterday_book.count == 0 %>
                  前日の投稿数が0のため計算できません
                <% else %>
               　  <% @the_day_before = @today_book.count / @yesterday_book.count.to_f %>
               　  <%= (@the_day_before * 100).round %>%
                <% end %>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
      
      <div class = 'table_width'>
       <table class="table table-bordered text-center">
        <thead>
         <tr>
          <th>今週の投稿数</th>
          <th>前週の投稿数</th>
          <th>前週比</th>
         </tr>
        </thead>
        <tbody>
         <tr>
         　<td><%= @this_week_book.count %></td>
         　<td><%= @last_week_book.count %></td>
         　<td>
           <% if @last_week_book.count == 0 %>
            前週の投稿数が0のため計算できません
           <% else %>
           　<% @the_week_before = @this_week_book.count / @last_week_book.count.to_f %>
           　<%= (@the_week_before * 100).round %>%
           <% end %>
          </td>
         </tr>
        </tbody>
       </table>
      </div>
      
<!--過去一週間分の投稿数-->
      <div class = 'table_width'>
        <h3>7日間分の投稿数</h3>
        <table class="table table-bordered text-center">
          <thead>
            <tr class='text-nowrap'>
              <th>6日前</th>
              <th>5日前</th>
              <th>4日前</th>
              <th>3日前</th>
              <th>2日前</th>
              <th>1日前</th>
              <th>今日</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <% @days_ago.each do |days_ago| %>
                <td><%= days_ago %></td>
              <% end %>
                <td><%= @today_book.count %></td>
            </tr>
          </tbody>
        </table>
      </div>
    
    </div>
  </div>
</div>